version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: ticketing
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: your_password
      DB_NAME: ticketing
      JWT_SECRET: your_jwt_secret
      APP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["./app"]
volumes:
  db_data:
